spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leadme
    username: root
    password: user
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  rabbitmq:
    host: localhost
    port: 5672
    username: spring_user
    password: spring_pass
    listener:
      simple:
        acknowledge-mode: manual
    mq:
      queue:
        user-action: user-action-queue


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:rootpass@localhost:27017/leadme?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha