spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://localhost:3306/highfive
    username: root
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

kakao:
  client-id: affb0cd63ddd7c89859f6efa2f1701d8
  client-secret: DqVDxauU9aRsesIu1FAG7zwXKUGxSPKz
  redirect-uri: http://localhost:8080/auth/login/kakao

jwt:
  secret: asdlkfsdksdljfsdljfskldjfdslkfjslkfjsdlfjskljdslfjkdlfj
  accessToken-expiration: 36000000
  refreshToken-expiration: 3600000000000000

fastapi:
  host: http://localhost
  port: 8000