spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leadme?currentSchema=leadme
    username: root
    password: user
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  rabbitmq:
    host: localhost
    port: 5672
    username: spring_user
    password: spring_pass
    listener:
      simple:
        acknowledge-mode: manual
    mq:
      queue:
        user-action: user-action-queue


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:rootpass@localhost:27017/leadme?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

kakao:
  client-id: affb0cd63ddd7c89859f6efa2f1701d8
  client-secret: DqVDxauU9aRsesIu1FAG7zwXKUGxSPKz
  redirect-uri: http://localhost:8080/auth/login/kakao

jwt:
  secret: asdlkfsdksdljfsdljfskldjfdslkfjslkfjsdlfjskljdslfjkdlfj
  accessToken-expiration: 36000000
  refreshToken-expiration: 3600000000000000

fastapi:
  host: http://localhost
  port: 8000

queue:
  name: recommendation.weight.update

cloud:
  aws:
    s3:
      bucket: i don't know
    region:
      static: korea
    credentials:
      access-key: abcdefg
      access-secret-key: abcedfg