name: DEV_CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: 스프링 빌드 .jar 파일 생성
        run: ./gradlew clean build

      - name: Debug SSH Key
        run: echo "${{ secrets.DEV_SSH_KEY }}" | wc -l

      - name: EC2 기존 app 폴더 초기화
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            rm -rf ~/app

      - name: EC2에 build/libs 폴더 생성
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            if [ ! -d ~/app/src/main/java/org/highfive/backend/infra/docker/build/libs ]; then
              mkdir -p ~/app/src/main/java/org/highfive/backend/infra/docker/build/libs
            fi

      - name: 빌드된 JAR 파일 EC2로 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "~/app/src/main/java/org/highfive/backend/infra/docker/"

      - name: docker-compose 파일 EC2로 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "src/main/java/org/highfive/backend/infra/docker/*"
          target: "~/app"

      - name: .env 값 주입후, docker-compose 실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd ~/app/src/main/java/org/highfive/backend/infra/docker
            echo "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" > .env
            echo "JWT_SECRET=${{ secrets.DEV_JWT_SECRET }}" >> .env
            echo "DB_NAME=${{ secrets.DEV_DB_NAME }}" >> .env
            echo "DB_HOST=${{ secrets.DEV_DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DEV_DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DEV_DB_USER }}" >> .env
            echo "REDIS_HOST=${{ secrets.DEV_REDIS_HOST }}" >> .env
            echo "REDIS_PORT=${{ secrets.DEV_REDIS_PORT }}" >> .env
            echo "SERVER_PORT=${{ secrets.DEV_SERVER_PORT }}" >> .env
            echo "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> .env
            echo "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> .env
            echo "OAUTH_FE_REDIRECT_URI=${{ secrets.OAUTH_FE_REDIRECT_URI }}" >> .env
            echo "OAUTH_CLIENT_URI=${{ secrets.OAUTH_REDIRECT_URI }}" >> .env
            echo "JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}" >> .env
            echo "JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}" >> .env
            echo "RECOMMEND_SERVER_URL=${{ secrets.RECOMMEND_SERVER_URL }}" >> .env
            echo "RECOMMEND_SERVER_PORT=${{ secrets.RECOMMEND_SERVER_PORT }}" >> .env
            echo "MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env
            echo "MONGO_DB_HOST=${{ secrets.MONGO_DB_HOST }}" >> .env
            echo "MONGO_DB_PORT=${{ secrets.MONGO_DB_PORT }}" >> .env
            echo "RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}" >> .env
            echo "RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}" >> .env
            echo "RABBITMQ_UI_PORT=${{ secrets.RABBITMQ_UI_PORT }}" >> .env
            echo "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}" >> .env
            echo "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}" >> .env
            echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY}}" >> .env
            echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY}}" >> .env
            echo "SLACK_WEBHOOK_LOG=${{ secrets.SLACK_WEBHOOK_LOG }}" >> .env
            echo "LOKI_SERVER_IP=${{ secrets.LOKI_SERVER_IP }}" >> .env
            echo "OTEL_EXPORTER_OTLP_ENDPOINT=${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}" >> .env
            echo "OTEL_SERVICE_NAME=${{ secrets.OTEL_SERVICE_NAME }}" >> .env
            
            docker-compose --env-file .env -f docker-compose-dev.yml down -v
            docker image prune -f
            docker-compose --env-file .env -f docker-compose-dev.yml up -d --build