version: '3.8'

services:
  db:
    image: pgvector/pgvector:0.8.0-pg15
    container_name: local-postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - local-net
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: user
      POSTGRES_DB: leadme

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: spring_user
      RABBITMQ_DEFAULT_PASS: spring_pass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:6
    container_name: local-redis
    ports:
      - "6379:6379"
    networks:
      - local-net

  mongo:
    image: mongo:6.0
    container_name: local-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo-data:/data/db
    networks:
      - local-net

volumes:
  db-data:
  mongo-data:
  rabbitmq_data:

networks:
  local-net: