services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    network_mode: host
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /home/ec2-user/app-logs:/home/ec2-user/app/logs
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_CLIENT_URI: ${OAUTH_CLIENT_URI}
      OAUTH_FE_REDIRECT_URI: ${OAUTH_FE_REDIRECT_URI}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      RECOMMEND_SERVER_URL: ${RECOMMEND_SERVER_URL}
      RECOMMEND_SERVER_PORT: ${RECOMMEND_SERVER_PORT}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_UI_PORT: ${RABBITMQ_UI_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      SLACK_WEBHOOK_LOG: ${SLACK_WEBHOOK_LOG}
      LOKI_SEVER_IP: ${LOKI_SERVER_IP}
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_METRICS_EXPORTER: "none"

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /home/ec2-user/app-logs:/home/ec2-user/app-logs:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    environment:
      LOKI_SERVER_IP: ${LOKI_SERVER_IP}
    depends_on:
      - app
